### ISSUE TITLE
[Features] support other languages

### ISSUE THREAD

**Issue by ctf0** [alvesjtiago/hover-locales#1]
is it possible to add an option for both scopes & locales path ?

so now you can use the package with `ruby, blade, vue, etc...`

**Comment by alvesjtiago** [comment]
@ctf0 that's a great idea! Implementing it right now. I'll let you know as soon as it's ready so you can test it out.

**Comment by alvesjtiago** [comment]
@ctf0 done! Let me know if this is what you were looking for.
Closing for now but if this is not sufficient to support other frameworks and languages I'll open it again.

**Comment by ctf0** [comment]
awesome, is it possible to also configure the files ext ? i mean for something like laravel it could be `php / json`

**Comment by alvesjtiago** [comment]
@ctf0 sure! Give me a couple of minutes and I'll change it, update the docs and release a new version.

**Comment by alvesjtiago** [comment]
@ctf0 actually it might be a little trickier than that because according to the file type it would be needed to parse the file accordingly. Can you send me an example of a file you're using?

**Comment by ctf0** [comment]
sure https://github.com/ctf0/Lingo/blob/master/src/resources/lang/en/messages.php
